import { SessionProvider } from '@smart-safety-solutions/contexts';
import { ApiProvider } from '@smart-safety-solutions/apis';
import './global.css';

export const metadata = {
  title: 'Welcome to smart-safety-solutions-admin',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ApiProvider>
      <SessionProvider>
        <html lang="en">
          <body>{children}</body>
        </html>
      </SessionProvider>
    </ApiProvider>
  );
}
